import type { Metadata } from "next";
import "./globals.css";
import { Onest, Oswald, Inter, Jost, Unbounded } from "next/font/google";
import Header from "@/components/Header/Header";
import ScrollTop from "@/components/ui/ScrollTop";
import { SmoothScroll } from "@/components/ui/SmoothScroll/SmoothScroll";

import Footer from "@/components/Footer/Footer";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
});

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} ${inter.variable} ${jost.variable} ${unbounded.variable} ${onest.variable} h-full antialiased`}
    >
      <body>
        <Header />
        <SmoothScroll>
          <main>{children}</main>
          <Footer />
        </SmoothScroll>
        <ScrollTop />
      </body>
    </html>
  );
}
